<a href="https://colab.research.google.com/github/Arju-cmd/NLP_Models/blob/main/BERT%20Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install tensorflow-text

     |████████████████████████████████| 4.4 MB 5.1 MB/s 


In [3]:
import tensorflow_hub as hub
import tensorflow_text as text

In [4]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [5]:
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [6]:
text_test = ['nice movie indeed','I love python programming']
text_preprocessed = bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [7]:
text_preprocessed['input_mask']

# CLS nice movie indeed SEP , these tokens(CLS and SEP will be kept so there will be 5 tokens)

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [8]:
text_preprocessed['input_word_ids']

# CLS nice movie indeed SEP , below is the id from vocabulary next stage we will create word embeding. We can see CLS and SEP the numbers are fixed
# BERT uses CLS as a special token at the begining of each setence whereas SEP as a special token to separate two sentences or end single sentence

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [9]:
bert_model = hub.KerasLayer(encoder_url)

In [10]:
bert_results = bert_model(text_preprocessed)

In [11]:
bert_results.keys()

dict_keys(['default', 'sequence_output', 'pooled_output', 'encoder_outputs'])

In [12]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917738 , -0.21411897,  0.49769586, ...,  0.24465264,
        -0.4733446 ,  0.8175868 ],
       [-0.9171231 , -0.4793517 , -0.7865697 , ..., -0.6175174 ,
        -0.7102685 ,  0.92184305]], dtype=float32)>

In [13]:
# Above is the embeding vector which is contextual and meaningful

In [14]:
# here 2 in the o/p is two sentences
# nice movie indeed 0 0 0 0 0 0  <-- 128, nice will be having 768 vector representation, even zero will be represented in some context form of vector
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292045,  0.08567825,  0.14476831, ..., -0.09677072,
          0.08722124,  0.07711083],
        [ 0.17839359, -0.19006054,  0.50349426, ..., -0.05869837,
          0.32717103, -0.15578508],
        [ 0.18701509, -0.4338876 , -0.48875144, ..., -0.15502721,
          0.00145185, -0.24470924],
        ...,
        [ 0.12083094,  0.12884264,  0.46453515, ...,  0.07375512,
          0.17441988,  0.16522057],
        [ 0.07967873, -0.01190663,  0.5022542 , ...,  0.13777718,
          0.21002212,  0.006246  ],
        [-0.07212683, -0.28303462,  0.5903337 , ...,  0.47551897,
          0.1666851 , -0.08920346]],

       [[-0.07900583,  0.36335114, -0.21101587, ..., -0.17183755,
          0.16299762,  0.6724269 ],
        [ 0.2788354 ,  0.4371628 , -0.35764772, ..., -0.04463607,
          0.38315237,  0.5887981 ],
        [ 1.203767  ,  1.072702  ,  0.48408762, ...,  0.24921018,
          0.40730917,  0.40481803],
        ...,

In [15]:
len(bert_results['encoder_outputs'])

12

In [16]:
# we have used 12 encoder bert

In [17]:
bert_results['encoder_outputs'][0]

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.12901431,  0.00644743, -0.03614967, ...,  0.04999623,
          0.06149202, -0.02657533],
        [ 1.1753384 ,  1.2140783 ,  1.1569979 , ...,  0.1163436 ,
         -0.35855368, -0.40490177],
        [ 0.03859077,  0.53869975, -0.21089804, ...,  0.21858175,
          0.7260166 , -1.1158606 ],
        ...,
        [-0.07587027, -0.2542189 ,  0.7075511 , ...,  0.5054197 ,
         -0.18878676,  0.1502835 ],
        [-0.16066618, -0.2808967 ,  0.5759707 , ...,  0.52758545,
         -0.11141379,  0.02887546],
        [-0.04428162, -0.20279565,  0.5909356 , ...,  0.8133835 ,
         -0.39075807, -0.02601739]],

       [[ 0.18903583,  0.02752543, -0.06513743, ..., -0.00620208,
          0.15053886,  0.03165435],
        [ 0.59161484,  0.7589138 , -0.0724067 , ...,  0.6190398 ,
          0.82928866,  0.16161968],
        [ 1.4460827 ,  0.4460264 ,  0.4099026 , ...,  0.48255897,
          0.6269118 ,  0.13463427],
        ...,

In [18]:
#The last layer of 12the encoder is equals to sequence output
bert_results['encoder_outputs'][-1] == bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>